// Copyright (c) 2024 NIMA. See the AUTHORS file for more info
// This package is governed by an MIT License. Check the LICENSE file for more information.
// Auto-Generated File: DO NOT EDIT
//
// NIMA CODE: nima006

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint
@ffi.DefaultAsset('package:seagort/libseagort.so')
library seagort;

import 'dart:ffi' as ffi;

@ffi.Native<ffi.Pointer<ffi.Char> Function(ffi.Pointer<ffi.Char>)>(
    symbol: 'compile_js')
external ffi.Pointer<ffi.Char> compile_js(
  ffi.Pointer<ffi.Char> code,
);
